name: Deploy Velo
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Install WASM Tools
        run: dotnet workload install wasm-tools-net7

      - name: Restore Workloads
        run: dotnet workload restore

      - name: Publish
        run: dotnet publish -c Release -o output

      - name: Fix paths and Integrity
        run: |
          # 1. Sistema il base href
          sed -i 's/<base href="\/" \/>/<base href="\/VELO-Image-Size-Optimizer\/" \/>/g' output/wwwroot/index.html
          
          # 2. Rimuove totalmente i controlli di integrità (Fix definitivo per l'errore SRI)
          # Questo comando elimina la proprietà "integrity" e il suo valore dal JSON
          sed -i 's/"integrity":\s*"[^"]*",//g' output/wwwroot/_framework/blazor.boot.json
          sed -i 's/"integrity":\s*"[^"]*"//g' output/wwwroot/_framework/blazor.boot.json
          
          # 3. Fix per 404 e Jekyll
          cp output/wwwroot/index.html output/wwwroot/404.html
          touch output/wwwroot/.nojekyll